### ISSUE TITLE
Kindly  Add README.md

### ISSUE THREAD

**Issue by dalvia62** [ashwini0529/startup-quotes#7]
You can explain your whole project throw 
Readme.md 

we can get a step to produce the layout 

Thank you

**Comment by ashwini0529** [comment]
Sure @dalvia62 !

**Comment by dalvia62** [comment]
Thanks @ashwini0529

**Comment by ghost** [comment]
doing it

**Comment by ghost** [comment]
done

**Comment by dalvia62** [comment]
> done

Thanks
